// Fun random name generator for deployments
const adjectives = [
  "Mighty",
  "Swift",
  "Brave",
  "Clever",
  "Happy",
  "Jolly",
  "Noble",
  "Epic",
  "Cosmic",
  "Stellar",
  "Quantum",
  "Electric",
  "Turbo",
  "Super",
  "Ultra",
  "Golden",
  "Silver",
  "Crystal",
  "Diamond",
  "Ruby",
  "Emerald",
  "Sapphire",
  "Ancient",
  "Modern",
  "Future",
  "Cyber",
  "Digital",
  "Virtual",
  "Hyper",
  "Thunder",
  "Lightning",
  "Storm",
  "Solar",
  "Lunar",
  "Nebula",
  "Galaxy",
  "Mystic",
  "Magic",
  "Enchanted",
  "Legendary",
  "Mythic",
  "Heroic",
  "Valiant",
  "Speedy",
  "Rapid",
  "Quick",
  "Agile",
  "Dynamic",
  "Energetic",
  "Vibrant",
  "Brilliant",
  "Radiant",
  "Glowing",
  "Shining",
  "Blazing",
  "Burning",
  "Flaming",
  "Arctic",
  "Frozen",
  "Cool",
  "Chill",
  "Frosty",
  "Icy",
  "Polar",
  "Wild",
  "Fierce",
  "Bold",
  "Daring",
  "Fearless",
  "Mighty",
  "Powerful",
];

const nouns = [
  "Phoenix",
  "Dragon",
  "Griffin",
  "Pegasus",
  "Unicorn",
  "Kraken",
  "Hydra",
  "Eagle",
  "Falcon",
  "Hawk",
  "Raven",
  "Owl",
  "Wolf",
  "Lion",
  "Tiger",
  "Panther",
  "Jaguar",
  "Cheetah",
  "Bear",
  "Shark",
  "Dolphin",
  "Whale",
  "Warrior",
  "Knight",
  "Samurai",
  "Ninja",
  "Wizard",
  "Sorcerer",
  "Mage",
  "Rocket",
  "Comet",
  "Meteor",
  "Star",
  "Planet",
  "Moon",
  "Sun",
  "Thunder",
  "Storm",
  "Wind",
  "Fire",
  "Wave",
  "Mountain",
  "Valley",
  "Blade",
  "Sword",
  "Shield",
  "Arrow",
  "Spear",
  "Hammer",
  "Axe",
  "Crystal",
  "Diamond",
  "Ruby",
  "Emerald",
  "Sapphire",
  "Opal",
  "Pearl",
  "Engine",
  "Turbine",
  "Generator",
  "Reactor",
  "Core",
  "Matrix",
  "Nexus",
  "Beacon",
  "Signal",
  "Pulse",
  "Wave",
  "Beam",
  "Ray",
  "Flash",
  "Voyage",
  "Journey",
  "Quest",
  "Mission",
  "Adventure",
  "Expedition",
  "Odyssey",
  "Force",
  "Power",
  "Energy",
  "Spirit",
  "Essence",
  "Element",
  "Aura",
];

export function generateRandomDeploymentName(): string {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const number = Math.floor(Math.random() * 9000) + 1000; // 4-digit number between 1000-9999

  return `${adjective}-${noun}-${number}`;
}

export function generateFunName(): string {
  // Alternative simpler version without numbers
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];

  return `${adjective} ${noun}`;
}
