/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestMonacoDirectImport } from './routes/test-monaco-direct'
import { Route as TestJsonEditorImport } from './routes/test-json-editor'
import { Route as testDeviceSelectionImport } from './routes/__test-device-selection'
import { Route as IndexImport } from './routes/index'
import { Route as NetworksIndexImport } from './routes/networks/index'
import { Route as DomainsIndexImport } from './routes/domains/index'
import { Route as DevicesIndexImport } from './routes/devices/index'
import { Route as DeploymentsIndexImport } from './routes/deployments/index'
import { Route as DomainsIdImport } from './routes/domains/$id'
import { Route as DevicesIdImport } from './routes/devices/$id'
import { Route as DeploymentsJobsImport } from './routes/deployments/jobs'
import { Route as DebugNetworkJobsImport } from './routes/debug/network-jobs'
import { Route as DebugDeviceJobsImport } from './routes/debug/device-jobs'
import { Route as NetworksDebugIdImport } from './routes/networks/debug.$id'
import { Route as DevicesDebugIdImport } from './routes/devices/debug.$id'
import { Route as DeploymentsDebugExecutionIdImport } from './routes/deployments/debug.$executionId'

// Create/Update Routes

const TestMonacoDirectRoute = TestMonacoDirectImport.update({
  id: '/test-monaco-direct',
  path: '/test-monaco-direct',
  getParentRoute: () => rootRoute,
} as any)

const TestJsonEditorRoute = TestJsonEditorImport.update({
  id: '/test-json-editor',
  path: '/test-json-editor',
  getParentRoute: () => rootRoute,
} as any)

const testDeviceSelectionRoute = testDeviceSelectionImport.update({
  id: '/__test-device-selection',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NetworksIndexRoute = NetworksIndexImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => rootRoute,
} as any)

const DomainsIndexRoute = DomainsIndexImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRoute,
} as any)

const DevicesIndexRoute = DevicesIndexImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsIndexRoute = DeploymentsIndexImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRoute,
} as any)

const DomainsIdRoute = DomainsIdImport.update({
  id: '/domains/$id',
  path: '/domains/$id',
  getParentRoute: () => rootRoute,
} as any)

const DevicesIdRoute = DevicesIdImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsJobsRoute = DeploymentsJobsImport.update({
  id: '/deployments/jobs',
  path: '/deployments/jobs',
  getParentRoute: () => rootRoute,
} as any)

const DebugNetworkJobsRoute = DebugNetworkJobsImport.update({
  id: '/debug/network-jobs',
  path: '/debug/network-jobs',
  getParentRoute: () => rootRoute,
} as any)

const DebugDeviceJobsRoute = DebugDeviceJobsImport.update({
  id: '/debug/device-jobs',
  path: '/debug/device-jobs',
  getParentRoute: () => rootRoute,
} as any)

const NetworksDebugIdRoute = NetworksDebugIdImport.update({
  id: '/networks/debug/$id',
  path: '/networks/debug/$id',
  getParentRoute: () => rootRoute,
} as any)

const DevicesDebugIdRoute = DevicesDebugIdImport.update({
  id: '/devices/debug/$id',
  path: '/devices/debug/$id',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsDebugExecutionIdRoute =
  DeploymentsDebugExecutionIdImport.update({
    id: '/deployments/debug/$executionId',
    path: '/deployments/debug/$executionId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__test-device-selection': {
      id: '/__test-device-selection'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof testDeviceSelectionImport
      parentRoute: typeof rootRoute
    }
    '/test-json-editor': {
      id: '/test-json-editor'
      path: '/test-json-editor'
      fullPath: '/test-json-editor'
      preLoaderRoute: typeof TestJsonEditorImport
      parentRoute: typeof rootRoute
    }
    '/test-monaco-direct': {
      id: '/test-monaco-direct'
      path: '/test-monaco-direct'
      fullPath: '/test-monaco-direct'
      preLoaderRoute: typeof TestMonacoDirectImport
      parentRoute: typeof rootRoute
    }
    '/debug/device-jobs': {
      id: '/debug/device-jobs'
      path: '/debug/device-jobs'
      fullPath: '/debug/device-jobs'
      preLoaderRoute: typeof DebugDeviceJobsImport
      parentRoute: typeof rootRoute
    }
    '/debug/network-jobs': {
      id: '/debug/network-jobs'
      path: '/debug/network-jobs'
      fullPath: '/debug/network-jobs'
      preLoaderRoute: typeof DebugNetworkJobsImport
      parentRoute: typeof rootRoute
    }
    '/deployments/jobs': {
      id: '/deployments/jobs'
      path: '/deployments/jobs'
      fullPath: '/deployments/jobs'
      preLoaderRoute: typeof DeploymentsJobsImport
      parentRoute: typeof rootRoute
    }
    '/devices/$id': {
      id: '/devices/$id'
      path: '/devices/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof DevicesIdImport
      parentRoute: typeof rootRoute
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/domains/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdImport
      parentRoute: typeof rootRoute
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsIndexImport
      parentRoute: typeof rootRoute
    }
    '/networks/': {
      id: '/networks/'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksIndexImport
      parentRoute: typeof rootRoute
    }
    '/deployments/debug/$executionId': {
      id: '/deployments/debug/$executionId'
      path: '/deployments/debug/$executionId'
      fullPath: '/deployments/debug/$executionId'
      preLoaderRoute: typeof DeploymentsDebugExecutionIdImport
      parentRoute: typeof rootRoute
    }
    '/devices/debug/$id': {
      id: '/devices/debug/$id'
      path: '/devices/debug/$id'
      fullPath: '/devices/debug/$id'
      preLoaderRoute: typeof DevicesDebugIdImport
      parentRoute: typeof rootRoute
    }
    '/networks/debug/$id': {
      id: '/networks/debug/$id'
      path: '/networks/debug/$id'
      fullPath: '/networks/debug/$id'
      preLoaderRoute: typeof NetworksDebugIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof testDeviceSelectionRoute
  '/test-json-editor': typeof TestJsonEditorRoute
  '/test-monaco-direct': typeof TestMonacoDirectRoute
  '/debug/device-jobs': typeof DebugDeviceJobsRoute
  '/debug/network-jobs': typeof DebugNetworkJobsRoute
  '/deployments/jobs': typeof DeploymentsJobsRoute
  '/devices/$id': typeof DevicesIdRoute
  '/domains/$id': typeof DomainsIdRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/devices': typeof DevicesIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/networks': typeof NetworksIndexRoute
  '/deployments/debug/$executionId': typeof DeploymentsDebugExecutionIdRoute
  '/devices/debug/$id': typeof DevicesDebugIdRoute
  '/networks/debug/$id': typeof NetworksDebugIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof testDeviceSelectionRoute
  '/test-json-editor': typeof TestJsonEditorRoute
  '/test-monaco-direct': typeof TestMonacoDirectRoute
  '/debug/device-jobs': typeof DebugDeviceJobsRoute
  '/debug/network-jobs': typeof DebugNetworkJobsRoute
  '/deployments/jobs': typeof DeploymentsJobsRoute
  '/devices/$id': typeof DevicesIdRoute
  '/domains/$id': typeof DomainsIdRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/devices': typeof DevicesIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/networks': typeof NetworksIndexRoute
  '/deployments/debug/$executionId': typeof DeploymentsDebugExecutionIdRoute
  '/devices/debug/$id': typeof DevicesDebugIdRoute
  '/networks/debug/$id': typeof NetworksDebugIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__test-device-selection': typeof testDeviceSelectionRoute
  '/test-json-editor': typeof TestJsonEditorRoute
  '/test-monaco-direct': typeof TestMonacoDirectRoute
  '/debug/device-jobs': typeof DebugDeviceJobsRoute
  '/debug/network-jobs': typeof DebugNetworkJobsRoute
  '/deployments/jobs': typeof DeploymentsJobsRoute
  '/devices/$id': typeof DevicesIdRoute
  '/domains/$id': typeof DomainsIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/deployments/debug/$executionId': typeof DeploymentsDebugExecutionIdRoute
  '/devices/debug/$id': typeof DevicesDebugIdRoute
  '/networks/debug/$id': typeof NetworksDebugIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/test-json-editor'
    | '/test-monaco-direct'
    | '/debug/device-jobs'
    | '/debug/network-jobs'
    | '/deployments/jobs'
    | '/devices/$id'
    | '/domains/$id'
    | '/deployments'
    | '/devices'
    | '/domains'
    | '/networks'
    | '/deployments/debug/$executionId'
    | '/devices/debug/$id'
    | '/networks/debug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/test-json-editor'
    | '/test-monaco-direct'
    | '/debug/device-jobs'
    | '/debug/network-jobs'
    | '/deployments/jobs'
    | '/devices/$id'
    | '/domains/$id'
    | '/deployments'
    | '/devices'
    | '/domains'
    | '/networks'
    | '/deployments/debug/$executionId'
    | '/devices/debug/$id'
    | '/networks/debug/$id'
  id:
    | '__root__'
    | '/'
    | '/__test-device-selection'
    | '/test-json-editor'
    | '/test-monaco-direct'
    | '/debug/device-jobs'
    | '/debug/network-jobs'
    | '/deployments/jobs'
    | '/devices/$id'
    | '/domains/$id'
    | '/deployments/'
    | '/devices/'
    | '/domains/'
    | '/networks/'
    | '/deployments/debug/$executionId'
    | '/devices/debug/$id'
    | '/networks/debug/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  testDeviceSelectionRoute: typeof testDeviceSelectionRoute
  TestJsonEditorRoute: typeof TestJsonEditorRoute
  TestMonacoDirectRoute: typeof TestMonacoDirectRoute
  DebugDeviceJobsRoute: typeof DebugDeviceJobsRoute
  DebugNetworkJobsRoute: typeof DebugNetworkJobsRoute
  DeploymentsJobsRoute: typeof DeploymentsJobsRoute
  DevicesIdRoute: typeof DevicesIdRoute
  DomainsIdRoute: typeof DomainsIdRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  NetworksIndexRoute: typeof NetworksIndexRoute
  DeploymentsDebugExecutionIdRoute: typeof DeploymentsDebugExecutionIdRoute
  DevicesDebugIdRoute: typeof DevicesDebugIdRoute
  NetworksDebugIdRoute: typeof NetworksDebugIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  testDeviceSelectionRoute: testDeviceSelectionRoute,
  TestJsonEditorRoute: TestJsonEditorRoute,
  TestMonacoDirectRoute: TestMonacoDirectRoute,
  DebugDeviceJobsRoute: DebugDeviceJobsRoute,
  DebugNetworkJobsRoute: DebugNetworkJobsRoute,
  DeploymentsJobsRoute: DeploymentsJobsRoute,
  DevicesIdRoute: DevicesIdRoute,
  DomainsIdRoute: DomainsIdRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  NetworksIndexRoute: NetworksIndexRoute,
  DeploymentsDebugExecutionIdRoute: DeploymentsDebugExecutionIdRoute,
  DevicesDebugIdRoute: DevicesDebugIdRoute,
  NetworksDebugIdRoute: NetworksDebugIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__test-device-selection",
        "/test-json-editor",
        "/test-monaco-direct",
        "/debug/device-jobs",
        "/debug/network-jobs",
        "/deployments/jobs",
        "/devices/$id",
        "/domains/$id",
        "/deployments/",
        "/devices/",
        "/domains/",
        "/networks/",
        "/deployments/debug/$executionId",
        "/devices/debug/$id",
        "/networks/debug/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__test-device-selection": {
      "filePath": "__test-device-selection.tsx"
    },
    "/test-json-editor": {
      "filePath": "test-json-editor.tsx"
    },
    "/test-monaco-direct": {
      "filePath": "test-monaco-direct.tsx"
    },
    "/debug/device-jobs": {
      "filePath": "debug/device-jobs.tsx"
    },
    "/debug/network-jobs": {
      "filePath": "debug/network-jobs.tsx"
    },
    "/deployments/jobs": {
      "filePath": "deployments/jobs.tsx"
    },
    "/devices/$id": {
      "filePath": "devices/$id.tsx"
    },
    "/domains/$id": {
      "filePath": "domains/$id.tsx"
    },
    "/deployments/": {
      "filePath": "deployments/index.tsx"
    },
    "/devices/": {
      "filePath": "devices/index.tsx"
    },
    "/domains/": {
      "filePath": "domains/index.tsx"
    },
    "/networks/": {
      "filePath": "networks/index.tsx"
    },
    "/deployments/debug/$executionId": {
      "filePath": "deployments/debug.$executionId.tsx"
    },
    "/devices/debug/$id": {
      "filePath": "devices/debug.$id.tsx"
    },
    "/networks/debug/$id": {
      "filePath": "networks/debug.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
